-- Run this entire file in Supabase Dashboard > SQL Editor.
create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  amount numeric(16,2) not null check (amount > 0), date date,
  payment_method text not null default 'ငွေသား', paid_by text not null check (paid_by in ('မတည်ငွေ','အိုက်ပီ','အိုက် နောင့်')),
  category text not null, note text not null default '', created_at timestamptz not null default now()
);
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer text not null, company text not null default '', date date not null, timber_type text not null default '',
  quantity_tons numeric(14,3) not null check (quantity_tons > 0), sold_tons numeric(14,3) not null default 0 check (sold_tons >= 0 and sold_tons <= quantity_tons),
  unit_price numeric(16,2) not null default 0 check (unit_price >= 0), paid_amount numeric(16,2) not null default 0 check (paid_amount >= 0),
  status text not null default 'New', created_at timestamptz not null default now()
);
create table if not exists public.timber (
  id bigint generated by default as identity primary key, name text not null unique,
  whole_price numeric(16,2) not null default 0, sawn_price numeric(16,2) not null default 0, stock_tons numeric(14,3) not null default 0
);
create table if not exists public.taxes (
  id bigint generated by default as identity primary key, date date not null, description text not null,
  amount numeric(16,2) not null, note text not null default '', created_at timestamptz not null default now()
);
create table if not exists public.sessions (
  token text primary key, username text not null, role text not null check (role in ('admin','user')),
  expires_at timestamptz not null, created_at timestamptz not null default now()
);
create index if not exists expenses_date_idx on public.expenses(date desc);
create index if not exists orders_date_idx on public.orders(date desc);
create index if not exists sessions_expiry_idx on public.sessions(expires_at);
alter table public.expenses enable row level security;
alter table public.orders enable row level security;
alter table public.timber enable row level security;
alter table public.taxes enable row level security;
alter table public.sessions enable row level security;
-- No browser policies are created. Only Netlify Functions using the protected service-role key can access these tables.
insert into public.timber(name) values ('ကျွန်း'),('ပျဉ်းကတိုး'),('အင်') on conflict(name) do nothing;

-- Safe to run on projects created with an earlier version of this schema.
-- Google Sheets expense rows may intentionally have an unknown/blank date.
alter table public.expenses alter column date drop not null;
